language: android
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - extra-android-m2repository
  - android-25
  - sys-img-armeabi-v7a-android-17

before_install:
- chmod +x .buildscript/deploy_snapshot.sh
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-17 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
jdk:
- oraclejdk8
licenses:
- android-sdk-license-.+
- android-sdk-license-c81a61d9
env:
  global:
  - MALLOC_ARENA_MAX=2
  - secure: gMFLK1oOnrmKo2BQyuc4q5JNbO9yZNzGXujUjMDZqY80PM17u1NHH+FtMtqHltGdHlysQGWOVEgCCaXKSjzUR/5oWX3Rx2o36sxFeFJTnv6Og1IfYaT+30yMNCw9dZwBgL/f9+MUcJGyg17Y4YJKiKP8f+2Zj8Cem8a1tTOv7z0=
  - secure: EtsL8IYW/+QFowKy/pM1pfc6XBz19AEPRv9+3I3vdHbLNzrEgAcQG/sfWwSwG8N9SyQ9HlgFpy+a4rT9y+vcT52izRviZbLKepCiGk2XyCrBasRy0ncbZBk4Mss1JPP2OFatsiEfEOrFo5rt1CnWapMUOwE7X5blCjrLtEjZRSA=
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: required
script: ./gradlew build cAT --stacktrace
# after_success:
# - ".buildscript/deploy_snapshot.sh"
cache:
  directories:
  - "$HOME/.gradle"


after_failure:
  - cat /home/travis/build/sockeqwe/mosby/mvp/build/outputs/lint-results-debug.xml
  - cat /home/travis/build/sockeqwe/mosby/viewstate/build/outputs/lint-results-debug.xml

