language: android
android:
  components:
  - build-tools-23.0.3
  - extra-android-m2repository
  - android-23
before_install:
- chmod +x .buildscript/deploy_snapshot.sh
jdk:
- oraclejdk8
licenses:
- android-sdk-license-.+
env:
  global:
  - MALLOC_ARENA_MAX=2
  - secure: gMFLK1oOnrmKo2BQyuc4q5JNbO9yZNzGXujUjMDZqY80PM17u1NHH+FtMtqHltGdHlysQGWOVEgCCaXKSjzUR/5oWX3Rx2o36sxFeFJTnv6Og1IfYaT+30yMNCw9dZwBgL/f9+MUcJGyg17Y4YJKiKP8f+2Zj8Cem8a1tTOv7z0=
  - secure: EtsL8IYW/+QFowKy/pM1pfc6XBz19AEPRv9+3I3vdHbLNzrEgAcQG/sfWwSwG8N9SyQ9HlgFpy+a4rT9y+vcT52izRviZbLKepCiGk2XyCrBasRy0ncbZBk4Mss1JPP2OFatsiEfEOrFo5rt1CnWapMUOwE7X5blCjrLtEjZRSA=
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: required
script: ./gradlew build --stacktrace
after_success:
- ".buildscript/deploy_snapshot.sh"
cache:
  directories:
  - "$HOME/.gradle"
